### Site info:

title : 修路的命水
tagline: 风水还是要看，成一是真的呢
author: winkey Li
email: wwwgto@qq.com
description: "winkey 的个人博客."
keywords: "java, javascript, css, html, C#, mysql, mongodb, nginx, liunx, android, ios, winkey Li"
url: "http://blog.winlv.com" # the base hostname & protocol for your site
locale: zh_CN

### Personal info and site tools info:
#twitter_username: winkey
#github_username:  winkey
disqus_shortname: winkey
favicon:     "/images/favicon.ico"
#touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)
#aboutme: Hi, this is Lijia Yu.  # these are shown on aboutme-sidebar.
#aboutme_photo: https://i.imgur.com/15BT1.jpg # your photo.


### Site setting:
ShowContactInfo: "False"
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "

### your Blogroll info, only name can shown on the page.

Blogroll:
   - name: vulcan
     href: https://github.com/vulcan
     title: 技术大牛，坐标深圳，本来想指向他博客的，好象关闭了。
   - name: vicent
     href: http://blog.withouz.com/
     title: 用友深圳创新码民，伪90后技术男，坐标深圳。
### Build settings
markdown: kramdown
kramdown:
        input: GFM
        syntax_highlighter: rouge
#highlighter: pygments
gems: [jekyll-paginate]
paginate: 5
exclude: [Rakefile]
